# boot.py -- auto-generated by ESP32 MicroPython Dev Station
# WiFi + WebREPL + hostname configuration

import network
import time

# Set hostname BEFORE activating interface (required for mDNS hostname.local resolution)
network.hostname("{{HOSTNAME}}")

# Connect to WiFi
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
if not wlan.isconnected():
    wlan.connect("{{SSID}}", "{{PASSWORD}}")
    for _ in range(20):  # 10 second timeout (20 * 0.5s)
        if wlan.isconnected():
            break
        time.sleep(0.5)

if wlan.isconnected():
    print("WiFi connected:", wlan.ifconfig()[0])
else:
    print("WiFi connection failed -- board continues without network")

# Start WebREPL (password set programmatically, no webrepl_cfg.py needed)
try:
    import webrepl
    webrepl.start(password="{{WEBREPL_PASSWORD}}")
except Exception as e:
    print("WebREPL start failed:", e)
